apiVersion: apps/v1
kind: Deployment
metadata:
  name: ussd-country-api-deployment
  labels:
    app: ussd-country-api
spec:
  replicas: 1
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      name: ussd-country-api
      labels:
        app: ussd-country-api
    spec:
      containers:
      - name: ussd-country-api-kenya
        image: crequity.azurecr.io/ussd/country-api-ke-prod:#{Build.BuildId}#
        imagePullPolicy: Always
        resources:
            requests:
              memory: "1024Mi"
              cpu: "200m"
            # limits:
            #   memory: "2048Mi"
            #   cpu: "400m"
        ports:
            - name: kenya-http
              containerPort: 20254
        env:
        - name: SETTINGS_PATH
          value: menumanager_country_api.settings.production
        - name: DJANGO_SETTINGS_MODULE
          value: menumanager_country_api.settings.production
        - name: SECRET_KEY
          value: #{USSD-COUNTRY-SECRET-KEY}#
        - name: REDIS_HOST
          value: #{USSD-REDIS-HOSTNAME}#
        - name: REDIS_PASS
          value: #{USSD-REDIS-KEY}#
        - name: REDIS_PORT
          value: "6379"
        - name: REDIS_SSL
          value: "False"
        - name: REDIS_SSL_CERT
          value: #{REDIS-SSL-CERT}#
        - name: REDIS_NON_CLUSTERED_HOST
          value: #{USSD-REDIS-NON-CLUSTERED-HOSTNAME}#
        - name: REDIS_NON_CLUSTERED_PASS
          value: #{USSD-REDIS-NON-CLUSTERED-KEY}#
        - name: REDIS_NON_CLUSTERED_PORT
          value: "6380"
        - name: REDIS_NON_CLUSTERED_SSL
          value: "True"
        - name: SERVICE_BASE_PORT
          value: "20000"
        - name: CACHE_MENU_KEY_PREFIX
          value: "menus"
        - name: DATABASE_NAME
          value: #{USSD-KE-DATABASE-NAME}#
        - name: COUNTRY_CODE
          value: "254"
        - name: PIN_RESET_SCREEN
          value: "PinResetIDNumberScreenKE"
        - name: HOME_MENU_SCREEN
          value: "MainMenuScreenKE"

      - name: ussd-country-api-rwanda
        image: crequity.azurecr.io/ussd/country-api-rw-prod:#{Build.BuildId}#
        imagePullPolicy: Always
        resources:
            requests:
              memory: "1024Mi"
              cpu: "200m"
            # limits:
            #   memory: "2048Mi"
            #   cpu: "400m"
        ports:
            - name: rwanda-http
              containerPort: 20250
        env:
        - name: SETTINGS_PATH
          value: menumanager_country_api.settings.production
        - name: DJANGO_SETTINGS_MODULE
          value: menumanager_country_api.settings.production
        - name: SECRET_KEY
          value: #{USSD-COUNTRY-SECRET-KEY}#
        - name: REDIS_HOST
          value: #{USSD-REDIS-HOSTNAME}#
        - name: REDIS_PASS
          value: #{USSD-REDIS-KEY}#
        - name: REDIS_PORT
          value: "6379"
        - name: REDIS_SSL
          value: "False"
        - name: REDIS_SSL_CERT
          value: #{REDIS-SSL-CERT}#
        - name: REDIS_NON_CLUSTERED_HOST
          value: #{USSD-REDIS-NON-CLUSTERED-HOSTNAME}#
        - name: REDIS_NON_CLUSTERED_PASS
          value: #{USSD-REDIS-NON-CLUSTERED-KEY}#
        - name: REDIS_NON_CLUSTERED_PORT
          value: "6380"
        - name: REDIS_NON_CLUSTERED_SSL
          value: "True"
        - name: SERVICE_BASE_PORT
          value: "20000"
        - name: CACHE_MENU_KEY_PREFIX
          value: "menus"
        - name: DATABASE_NAME
          value: #{USSD-RW-DATABASE-NAME}#
        - name: COUNTRY_CODE
          value: "250"
        - name: PIN_RESET_SCREEN
          value: "PinResetIDNumberScreenRW"
        - name: HOME_MENU_SCREEN
          value: "MainMenuScreenRW"

      - name: ussd-country-api-south-sudan
        image: crequity.azurecr.io/ussd/country-api-ss-prod:#{Build.BuildId}#
        imagePullPolicy: Always
        resources:
            requests:
              memory: "1024Mi"
              cpu: "200m"
            # limits:
            #   memory: "2048Mi"
            #   cpu: "400m"
        ports:
            - name: ss-http
              containerPort: 20211
        env:
        - name: SETTINGS_PATH
          value: menumanager_country_api.settings.production
        - name: DJANGO_SETTINGS_MODULE
          value: menumanager_country_api.settings.production
        - name: SECRET_KEY
          value: #{USSD-COUNTRY-SECRET-KEY}#
        - name: REDIS_HOST
          value: #{USSD-REDIS-HOSTNAME}#
        - name: REDIS_PASS
          value: #{USSD-REDIS-KEY}#
        - name: REDIS_PORT
          value: "6379"
        - name: REDIS_SSL
          value: "False"
        - name: REDIS_SSL_CERT
          value: #{REDIS-SSL-CERT}#
        - name: REDIS_NON_CLUSTERED_HOST
          value: #{USSD-REDIS-NON-CLUSTERED-HOSTNAME}#
        - name: REDIS_NON_CLUSTERED_PASS
          value: #{USSD-REDIS-NON-CLUSTERED-KEY}#
        - name: REDIS_NON_CLUSTERED_PORT
          value: "6380"
        - name: REDIS_NON_CLUSTERED_SSL
          value: "True"
        - name: SERVICE_BASE_PORT
          value: "20000"
        - name: CACHE_MENU_KEY_PREFIX
          value: "menus"
        - name: DATABASE_NAME
          value: #{USSD-SS-DATABASE-NAME}#
        - name: COUNTRY_CODE
          value: "211"
        - name: PIN_RESET_SCREEN
          value: "PinResetIDNumberScreenSS"
        - name: HOME_MENU_SCREEN
          value: "MainMenuScreenSS"

      - name: ussd-country-api-uganda
        image: crequity.azurecr.io/ussd/country-api-ug-prod:#{Build.BuildId}#
        imagePullPolicy: Always
        resources:
            requests:
              memory: "1024Mi"
              cpu: "200m"
            # limits:
            #   memory: "2048Mi"
            #   cpu: "400m"
        ports:
            - name: ug-http
              containerPort: 20256
        env:
        - name: SETTINGS_PATH
          value: menumanager_country_api.settings.production
        - name: DJANGO_SETTINGS_MODULE
          value: menumanager_country_api.settings.production
        - name: SECRET_KEY
          value: #{USSD-COUNTRY-SECRET-KEY}#
        - name: REDIS_HOST
          value: #{USSD-REDIS-HOSTNAME}#
        - name: REDIS_PASS
          value: #{USSD-REDIS-KEY}#
        - name: REDIS_PORT
          value: "6379"
        - name: REDIS_SSL
          value: "False"
        - name: REDIS_SSL_CERT
          value: #{REDIS-SSL-CERT}#
        - name: REDIS_NON_CLUSTERED_HOST
          value: #{USSD-REDIS-NON-CLUSTERED-HOSTNAME}#
        - name: REDIS_NON_CLUSTERED_PASS
          value: #{USSD-REDIS-NON-CLUSTERED-KEY}#
        - name: REDIS_NON_CLUSTERED_PORT
          value: "6380"
        - name: REDIS_NON_CLUSTERED_SSL
          value: "True"
        - name: SERVICE_BASE_PORT
          value: "20000"
        - name: CACHE_MENU_KEY_PREFIX
          value: "menus"
        - name: DATABASE_NAME
          value: #{USSD-UG-DATABASE-NAME}#
        - name: COUNTRY_CODE
          value: "256"
        - name: PIN_RESET_SCREEN
          value: "PinResetIDNumberScreenUG"
        - name: HOME_MENU_SCREEN
          value: "MainMenuScreenUG"

      - name: ussd-country-api-tanzania
        image: crequity.azurecr.io/ussd/country-api-tz-prod:#{Build.BuildId}#
        imagePullPolicy: Always
        resources:
            requests:
              memory: "1024Mi"
              cpu: "200m"
            # limits:
            #   memory: "2048Mi"
            #   cpu: "400m"
        ports:
            - name: tz-http
              containerPort: 20255
        env:
        - name: SETTINGS_PATH
          value: menumanager_country_api.settings.production
        - name: DJANGO_SETTINGS_MODULE
          value: menumanager_country_api.settings.production
        - name: SECRET_KEY
          value: #{USSD-COUNTRY-SECRET-KEY}#
        - name: REDIS_HOST
          value: #{USSD-REDIS-HOSTNAME}#
        - name: REDIS_PASS
          value: #{USSD-REDIS-KEY}#
        - name: REDIS_PORT
          value: "6379"
        - name: REDIS_SSL
          value: "False"
        - name: REDIS_SSL_CERT
          value: #{REDIS-SSL-CERT}#
        - name: REDIS_NON_CLUSTERED_HOST
          value: #{USSD-REDIS-NON-CLUSTERED-HOSTNAME}#
        - name: REDIS_NON_CLUSTERED_PASS
          value: #{USSD-REDIS-NON-CLUSTERED-KEY}#
        - name: REDIS_NON_CLUSTERED_PORT
          value: "6380"
        - name: REDIS_NON_CLUSTERED_SSL
          value: "True"
        - name: SERVICE_BASE_PORT
          value: "20000"
        - name: CACHE_MENU_KEY_PREFIX
          value: "menus"
        - name: DATABASE_NAME
          value: #{USSD-TZ-DATABASE-NAME}#
        - name: COUNTRY_CODE
          value: "255"
        - name: PIN_RESET_SCREEN
          value: "PinResetIDNumberScreenTZ"
        - name: HOME_MENU_SCREEN
          value: "MainMenuScreenTZ"
    
  selector:
    matchLabels:
      app: ussd-country-api

---

apiVersion: v1
kind: Service
metadata:
  name: ussd-country-api-service
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  ports:
    - name: kenya
      port: 20254
      targetPort: kenya-http
    - name: rwanda
      port: 20250
      targetPort: rwanda-http
    - name: south-sudan
      port: 20211
      targetPort: ss-http
    - name: uganda
      port: 20256
      targetPort: ug-http
    - name: tanzania
      port: 20255
      targetPort: tz-http
  selector:
    app: ussd-country-api