apiVersion: apps/v1
kind: Deployment
metadata:
  name: ussd-country-api-deployment
  labels:
    app: ussd-country-api
spec:
  replicas: 1
  minReadySeconds: 10
  strategy:
    # type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      name: ussd-country-api
      labels:
        app: ussd-country-api
    spec:
      containers:
      - name: ussd-country-api-kenya
        image: crequitydevtest.azurecr.io/ussd/country-api-ke-dev:#{Build.BuildId}#
        imagePullPolicy: Always
        resources:
            # requests:
            #   memory: "512Mi"
            #   cpu: "250m"
            # limits:
            #   memory: "1024Mi"
            #   cpu: "500m"
        ports:
            - name: kenya-http
              containerPort: 20254
        env:
        - name: SETTINGS_PATH
          value: menumanager_country_api.settings.production
        - name: DJANGO_SETTINGS_MODULE
          value: menumanager_country_api.settings.production
        - name: SECRET_KEY
          value: #{USSD-COUNTRY-SECRET-KEY}#
        - name: REDIS_RUNS_IN_CLUSTER
          value: "True"
        - name: REDIS_HOST
          value: #{USSD-REDIS-HOSTNAME}#
        - name: REDIS_PASS
          value: #{USSD-REDIS-KEY}#
        - name: REDIS_PORT
          value: "6380"
        - name: REDIS_SSL
          value: "True"
        - name: REDIS_SSL_CERT
          value: #{REDIS-SSL-CERT}#
        - name: REDIS_NON_CLUSTERED_HOST
          value: #{USSD-REDIS-NON-CLUSTERED-HOSTNAME}#
        - name: REDIS_NON_CLUSTERED_PASS
          value: #{USSD-REDIS-NON-CLUSTERED-KEY}#
        - name: REDIS_NON_CLUSTERED_PORT
          value: "6380"
        - name: REDIS_NON_CLUSTERED_SSL
          value: "True"
        - name: SERVICE_BASE_PORT
          value: "20000"
        - name: CACHE_MENU_KEY_PREFIX
          value: "menus"
        - name: CACHE_OMNI_KEY_PREFIX
          value: "OMNI"
        - name: DATABASE_NAME
          value: #{USSD-KE-DATABASE-NAME}#
        - name: COUNTRY_CODE
          value: "254"
        - name: PIN_RESET_SCREEN
          value: "PinResetIDNumberScreenKE"
        - name: HOME_MENU_SCREEN
          value: "MainMenuScreenKE"

          
      - name: ussd-country-api-rwanda
        image: crequitydevtest.azurecr.io/ussd/country-api-rw-dev:#{Build.BuildId}#
        imagePullPolicy: Always
        resources:
            # requests:
            #   memory: "512Mi"
            #   cpu: "250m"
            # limits:
            #   memory: "1024Mi"
            #   cpu: "500m"
        ports:
            - name: rwanda-http
              containerPort: 20250
        env:
        - name: SETTINGS_PATH
          value: menumanager_country_api.settings.production
        - name: DJANGO_SETTINGS_MODULE
          value: menumanager_country_api.settings.production
        - name: SECRET_KEY
          value: #{USSD-COUNTRY-SECRET-KEY}#
        - name: REDIS_RUNS_IN_CLUSTER
          value: "True"
        - name: REDIS_HOST
          value: #{USSD-REDIS-HOSTNAME}#
        - name: REDIS_PASS
          value: #{USSD-REDIS-KEY}#
        - name: REDIS_PORT
          value: "6380"
        - name: REDIS_SSL
          value: "True"
        - name: REDIS_SSL_CERT
          value: #{REDIS-SSL-CERT}#
        - name: REDIS_NON_CLUSTERED_HOST
          value: #{USSD-REDIS-NON-CLUSTERED-HOSTNAME}#
        - name: REDIS_NON_CLUSTERED_PASS
          value: #{USSD-REDIS-NON-CLUSTERED-KEY}#
        - name: REDIS_NON_CLUSTERED_PORT
          value: "6380"
        - name: REDIS_NON_CLUSTERED_SSL
          value: "True"
        - name: SERVICE_BASE_PORT
          value: "20000"
        - name: CACHE_MENU_KEY_PREFIX
          value: "menus"
        - name: CACHE_OMNI_KEY_PREFIX
          value: "OMNI"
        - name: DATABASE_NAME
          value: #{USSD-RW-DATABASE-NAME}#
        - name: COUNTRY_CODE
          value: "250"
        - name: PIN_RESET_SCREEN
          value: "PinResetIDNumberScreenRW"
        - name: HOME_MENU_SCREEN
          value: "MainMenuScreenRW"


      - name: ussd-country-api-south-sudan
        image: crequitydevtest.azurecr.io/ussd/country-api-ss-dev:#{Build.BuildId}#
        imagePullPolicy: Always
        resources:
            # requests:
            #   memory: "512Mi"
            #   cpu: "250m"
            # limits:
            #   memory: "1024Mi"
            #   cpu: "500m"
        ports:
            - name: ss-http
              containerPort: 20211
        env:
        - name: SETTINGS_PATH
          value: menumanager_country_api.settings.production
        - name: DJANGO_SETTINGS_MODULE
          value: menumanager_country_api.settings.production
        - name: SECRET_KEY
          value: #{USSD-COUNTRY-SECRET-KEY}#
        - name: REDIS_RUNS_IN_CLUSTER
          value: "True"
        - name: REDIS_HOST
          value: #{USSD-REDIS-HOSTNAME}#
        - name: REDIS_PASS
          value: #{USSD-REDIS-KEY}#
        - name: REDIS_PORT
          value: "6380"
        - name: REDIS_SSL
          value: "True"
        - name: REDIS_SSL_CERT
          value: #{REDIS-SSL-CERT}#
        - name: REDIS_NON_CLUSTERED_HOST
          value: #{USSD-REDIS-NON-CLUSTERED-HOSTNAME}#
        - name: REDIS_NON_CLUSTERED_PASS
          value: #{USSD-REDIS-NON-CLUSTERED-KEY}#
        - name: REDIS_NON_CLUSTERED_PORT
          value: "6380"
        - name: REDIS_NON_CLUSTERED_SSL
          value: "True"
        - name: SERVICE_BASE_PORT
          value: "20000"
        - name: CACHE_MENU_KEY_PREFIX
          value: "menus"
        - name: CACHE_OMNI_KEY_PREFIX
          value: "OMNI"
        - name: DATABASE_NAME
          value: #{USSD-SS-DATABASE-NAME}#
        - name: COUNTRY_CODE
          value: "211"
        - name: PIN_RESET_SCREEN
          value: "PinResetIDNumberScreenSS"
        - name: HOME_MENU_SCREEN
          value: "MainMenuScreenSS"


      - name: ussd-country-api-uganda
        image: crequitydevtest.azurecr.io/ussd/country-api-ug-dev:#{Build.BuildId}#
        imagePullPolicy: Always
        resources:
            # requests:
            #   memory: "512Mi"
            #   cpu: "250m"
            # limits:
            #   memory: "1024Mi"
            #   cpu: "500m"
        ports:
            - name: ug-http
              containerPort: 20256
        env:
        - name: SETTINGS_PATH
          value: menumanager_country_api.settings.production
        - name: DJANGO_SETTINGS_MODULE
          value: menumanager_country_api.settings.production
        - name: SECRET_KEY
          value: #{USSD-COUNTRY-SECRET-KEY}#
        - name: REDIS_RUNS_IN_CLUSTER
          value: "True"
        - name: REDIS_HOST
          value: #{USSD-REDIS-HOSTNAME}#
        - name: REDIS_PASS
          value: #{USSD-REDIS-KEY}#
        - name: REDIS_PORT
          value: "6380"
        - name: REDIS_SSL
          value: "True"
        - name: REDIS_SSL_CERT
          value: #{REDIS-SSL-CERT}#
        - name: REDIS_NON_CLUSTERED_HOST
          value: #{USSD-REDIS-NON-CLUSTERED-HOSTNAME}#
        - name: REDIS_NON_CLUSTERED_PASS
          value: #{USSD-REDIS-NON-CLUSTERED-KEY}#
        - name: REDIS_NON_CLUSTERED_PORT
          value: "6380"
        - name: REDIS_NON_CLUSTERED_SSL
          value: "True"
        - name: SERVICE_BASE_PORT
          value: "20000"
        - name: CACHE_MENU_KEY_PREFIX
          value: "menus"
        - name: CACHE_OMNI_KEY_PREFIX
          value: "OMNI"
        - name: DATABASE_NAME
          value: #{USSD-UG-DATABASE-NAME}#
        - name: COUNTRY_CODE
          value: "256"
        - name: PIN_RESET_SCREEN
          value: "PinResetIDNumberScreenUG"
        - name: HOME_MENU_SCREEN
          value: "MainMenuScreenUG"


      - name: ussd-country-api-tanzania
        image: crequitydevtest.azurecr.io/ussd/country-api-tz-dev:#{Build.BuildId}#
        imagePullPolicy: Always
        resources:
            # requests:
            #   memory: "512Mi"
            #   cpu: "250m"
            # limits:
            #   memory: "1024Mi"
            #   cpu: "500m"
        ports:
            - name: tz-http
              containerPort: 20255
        env:
        - name: SETTINGS_PATH
          value: menumanager_country_api.settings.production
        - name: DJANGO_SETTINGS_MODULE
          value: menumanager_country_api.settings.production
        - name: SECRET_KEY
          value: #{USSD-COUNTRY-SECRET-KEY}#
        - name: REDIS_RUNS_IN_CLUSTER
          value: "True"
        - name: REDIS_HOST
          value: #{USSD-REDIS-HOSTNAME}#
        - name: REDIS_PASS
          value: #{USSD-REDIS-KEY}#
        - name: REDIS_PORT
          value: "6380"
        - name: REDIS_SSL
          value: "True"
        - name: REDIS_SSL_CERT
          value: #{REDIS-SSL-CERT}#
        - name: REDIS_NON_CLUSTERED_HOST
          value: #{USSD-REDIS-NON-CLUSTERED-HOSTNAME}#
        - name: REDIS_NON_CLUSTERED_PASS
          value: #{USSD-REDIS-NON-CLUSTERED-KEY}#
        - name: REDIS_NON_CLUSTERED_PORT
          value: "6380"
        - name: REDIS_NON_CLUSTERED_SSL
          value: "True"
        - name: SERVICE_BASE_PORT
          value: "20000"
        - name: CACHE_MENU_KEY_PREFIX
          value: "menus"
        - name: CACHE_OMNI_KEY_PREFIX
          value: "OMNI"
        - name: DATABASE_NAME
          value: #{USSD-TZ-DATABASE-NAME}#
        - name: COUNTRY_CODE
          value: "255"
        - name: PIN_RESET_SCREEN
          value: "PinResetIDNumberScreenTZ"
        - name: HOME_MENU_SCREEN
          value: "MainMenuScreenTZ"


      - name: ussd-country-api-drc
        image: crequitydevtest.azurecr.io/ussd/country-api-drc-dev:#{Build.BuildId}#
        imagePullPolicy: Always
        resources:
          # requests:
          #   memory: "512Mi"
          #   cpu: "250m"
          # limits:
          #   memory: "1024Mi"
          #   cpu: "500m"
        ports:
          - name: drc-http
            containerPort: 20243
        env:
          - name: SETTINGS_PATH
            value: menumanager_country_api.settings.production
          - name: DJANGO_SETTINGS_MODULE
            value: menumanager_country_api.settings.production
          - name: SECRET_KEY
            value: #{USSD-COUNTRY-SECRET-KEY}#
          - name: REDIS_RUNS_IN_CLUSTER
            value: "True"
          - name: REDIS_HOST
            value: #{USSD-REDIS-HOSTNAME}#
          - name: REDIS_PASS
            value: #{USSD-REDIS-KEY}#
          - name: REDIS_PORT
            value: "6380"
          - name: REDIS_SSL
            value: "True"
          - name: REDIS_SSL_CERT
            value: #{REDIS-SSL-CERT}#
          - name: REDIS_NON_CLUSTERED_HOST
            value: #{USSD-REDIS-NON-CLUSTERED-HOSTNAME}#
          - name: REDIS_NON_CLUSTERED_PASS
            value: #{USSD-REDIS-NON-CLUSTERED-KEY}#
          - name: REDIS_NON_CLUSTERED_PORT
            value: "6380"
          - name: REDIS_NON_CLUSTERED_SSL
            value: "True"
          - name: REDIS_RUNS_IN_CLUSTER
            value: "True"
          - name: SERVICE_BASE_PORT
            value: "20000"
          - name: CACHE_MENU_KEY_PREFIX
            value: "menus"
          - name: CACHE_OMNI_KEY_PREFIX
            value: "OMNI"
          - name: DATABASE_NAME
            value: #{USSD-DRC-DATABASE-NAME}#
          - name: COUNTRY_CODE
            value: "243"
          - name: PIN_RESET_SCREEN
            value: "PinResetIDNumberScreenDRC"
          - name: HOME_MENU_SCREEN
            value: "MainMenuScreenDRC"

  selector:
    matchLabels:
      app: ussd-country-api

---

apiVersion: v1
kind: Service
metadata:
  name: ussd-country-api-service
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  ports:
    - name: kenya
      port: 20254
      targetPort: kenya-http
    - name: rwanda
      port: 20250
      targetPort: rwanda-http
    - name: south-sudan
      port: 20211
      targetPort: ss-http
    - name: uganda
      port: 20256
      targetPort: ug-http
    - name: tanzania
      port: 20255
      targetPort: tz-http
    - name: democratic-republic-of-the-congo
      port: 20243
      targetPort: drc-http
  selector:
    app: ussd-country-api

---

# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: ussd-country-api-ingress
#   annotations:
#     nginx.ingress.kubernetes.io/ssl-redirect: "false"
#     nginx.ingress.kubernetes.io/use-regex: "true"
#     nginx.ingress.kubernetes.io/enable-cors: "true"
#     nginx.ingress.kubernetes.io/cors-allow-origin: "*"
#     nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
#     nginx.ingress.kubernetes.io/cors-allow-methods: "*"    
# spec:
#   ingressClassName: nginx
#   rules:
#   - http:
#       paths:
#       - path: /api/menumanager_country_api/kenya(/|$)(.*)
#         pathType: Prefix
#         backend:
#           service:
#             name: ussd-country-api-service
#             port:
#               number: 20254
#       - path: /api/menumanager_country_api/rwanda(/|$)(.*)
#         pathType: Prefix
#         backend:
#           service:
#             name: ussd-country-api-service
#             port:
#               number: 20250
#       - path: /api/menumanager_country_api/south-sudan(/|$)(.*)
#         pathType: Prefix
#         backend:
#           service:
#             name: ussd-country-api-service
#             port:
#               number: 20211
#       - path: /api/menumanager_country_api/uganda(/|$)(.*)
#         pathType: Prefix
#         backend:
#           service:
#             name: ussd-country-api-service
#             port:
#               number: 20256                                           
#       - path: /api/menumanager_country_api/tanzania(/|$)(.*)
#         pathType: Prefix
#         backend:
#           service:
#             name: ussd-country-api-service
#             port:
#               number: 20255
