version: "3.9"

services:
  menu-country-api-ke:
    command: /opt/app/kenya-start-server.sh
    build:
      context: ./menumanager_country_api
      dockerfile: DockerfileKenya
    image: ussd/country-api-ke-prod:#{Build.BuildId}#
    container_name: menu_country_api_ke
    env_file: ./menumanager_country_api/.env_sample
    ports:
      - "20254:8010"
    volumes:
      - ./menumanager_country_api:/opt/app/menumanager_country_api

  menu-country-api-rw:
    command: /opt/app/rwanda-start-server.sh
    build:
      context: ./menumanager_country_api
      dockerfile: DockerfileRwanda
    image: ussd/country-api-rw-prod:#{Build.BuildId}#
    container_name: menu_country_api_ke
    env_file: ./menumanager_country_api/.env_sample
    ports:
      - "20250:8020"
    volumes:
      - ./menumanager_country_api:/opt/app/menumanager_country_api

  menu-country-api-ss:
    command: /opt/app/south-sudan-start-server.sh
    build:
      context: ./menumanager_country_api
      dockerfile: DockerfileSouthSudan
    image: ussd/country-api-ss-prod:#{Build.BuildId}#
    container_name: menu_country_api_ss
    env_file: ./menumanager_country_api/.env_sample
    ports:
      - "20211:8030"
    volumes:
      - ./menumanager_country_api:/opt/app/menumanager_country_api

  menu-country-api-ug:
    command: /opt/app/uganda-start-server.sh
    build:
      context: ./menumanager_country_api
      dockerfile: DockerfileUganda
    image: ussd/country-api-ug-prod:#{Build.BuildId}#
    container_name: menu_country_api_ug
    env_file: ./menumanager_country_api/.env_sample
    ports:
      - "20256:8040"
    volumes:
      - ./menumanager_country_api:/opt/app/menumanager_country_api

  menu-country-api-tz:
    command: /opt/app/tanzania-start-server.sh
    build:
      context: ./menumanager_country_api
      dockerfile: DockerfileTanzania
    image: ussd/country-api-tz-prod:#{Build.BuildId}#
    container_name: menu_country_api_tz
    env_file: ./menumanager_country_api/.env_sample
    ports:
      - "20255:8050"
    volumes:
      - ./menumanager_country_api:/opt/app/menumanager_country_api